#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.LogAnalyser
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="cerberus.fasttrackdb")]
	public partial class FastTrackDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FastTrackDataContext() : 
				base(global::Cerberus.LogAnalyser.Properties.Settings.Default.Cerberus_FastTrackConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FastTrackDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FastTrackDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FastTrackDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FastTrackDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Run> Runs
		{
			get
			{
				return this.GetTable<Run>();
			}
		}
		
		public System.Data.Linq.Table<strResult> strResults
		{
			get
			{
				return this.GetTable<strResult>();
			}
		}
		
		public System.Data.Linq.Table<strInfo> strInfos
		{
			get
			{
				return this.GetTable<strInfo>();
			}
		}
		
		[Function(Name="dbo.NewStrResult")]
		public int NewStrResult([Parameter(DbType="Int")] System.Nullable<int> strID, [Parameter(DbType="VarChar(8000)")] string message, [Parameter(DbType="Char(10)")] string result, [Parameter(DbType="Char(100)")] string checkname, [Parameter(DbType="Int")] ref System.Nullable<int> strResultID)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strID, message, result, checkname, strResultID);
			strResultID = ((System.Nullable<int>)(result1.GetParameterValue(4)));
			return ((int)(result1.ReturnValue));
		}
		
		[Function(Name="dbo.NewRun")]
		public int NewRun([Parameter(DbType="NVarChar(50)")] string user, [Parameter(DbType="Int")] ref System.Nullable<int> runID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, runID);
			runID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.NewStrInfo")]
		public int NewStrInfo([Parameter(DbType="Char(20)")] string build, [Parameter(DbType="VarChar(50)")] string project, [Parameter(DbType="VarChar(50)")] string locgroup, [Parameter(DbType="VarChar(100)")] string lcxfile, [Parameter(DbType="VarChar(MAX)")] string sourcestring, [Parameter(DbType="VarChar(8000)")] string comments, [Parameter(DbType="VarChar(512)")] string lsresid, [Parameter(DbType="VarChar(10)")] string targetCultrue, [Parameter(DbType="Int")] System.Nullable<int> runID, [Parameter(Name="StrID", DbType="Int")] ref System.Nullable<int> strID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), build, project, locgroup, lcxfile, sourcestring, comments, lsresid, targetCultrue, runID, strID);
			strID = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[Table(Name="dbo.Run")]
	public partial class Run
	{
		
		private int _id;
		
		private System.DateTime _runDate;
		
		private string _user;
		
		public Run()
		{
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[Column(Storage="_runDate", DbType="DateTime NOT NULL")]
		public System.DateTime runDate
		{
			get
			{
				return this._runDate;
			}
			set
			{
				if ((this._runDate != value))
				{
					this._runDate = value;
				}
			}
		}
		
		[Column(Name="[user]", Storage="_user", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				if ((this._user != value))
				{
					this._user = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.strResult")]
	public partial class strResult
	{
		
		private System.Nullable<int> _strID;
		
		private string _message;
		
		private string _result;
		
		private string _checkname;
		
		public strResult()
		{
		}
		
		[Column(Storage="_strID", DbType="Int")]
		public System.Nullable<int> strID
		{
			get
			{
				return this._strID;
			}
			set
			{
				if ((this._strID != value))
				{
					this._strID = value;
				}
			}
		}
		
		[Column(Storage="_message", DbType="VarChar(8000)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this._message = value;
				}
			}
		}
		
		[Column(Storage="_result", DbType="Char(10)")]
		public string result
		{
			get
			{
				return this._result;
			}
			set
			{
				if ((this._result != value))
				{
					this._result = value;
				}
			}
		}
		
		[Column(Storage="_checkname", DbType="Char(100)")]
		public string checkname
		{
			get
			{
				return this._checkname;
			}
			set
			{
				if ((this._checkname != value))
				{
					this._checkname = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.strInfo")]
	public partial class strInfo
	{
		
		private int _strID;
		
		private string _build;
		
		private string _project;
		
		private string _locgroup;
		
		private string _lcxfile;
		
		private string _sourcestring;
		
		private string _comments;
		
		private string _lsresid;
		
		private string _targetculture;
		
		private System.Nullable<int> _runID;
		
		public strInfo()
		{
		}
		
		[Column(Storage="_strID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int strID
		{
			get
			{
				return this._strID;
			}
			set
			{
				if ((this._strID != value))
				{
					this._strID = value;
				}
			}
		}
		
		[Column(Storage="_build", DbType="Char(20)")]
		public string build
		{
			get
			{
				return this._build;
			}
			set
			{
				if ((this._build != value))
				{
					this._build = value;
				}
			}
		}
		
		[Column(Storage="_project", DbType="VarChar(50)")]
		public string project
		{
			get
			{
				return this._project;
			}
			set
			{
				if ((this._project != value))
				{
					this._project = value;
				}
			}
		}
		
		[Column(Storage="_locgroup", DbType="VarChar(50)")]
		public string locgroup
		{
			get
			{
				return this._locgroup;
			}
			set
			{
				if ((this._locgroup != value))
				{
					this._locgroup = value;
				}
			}
		}
		
		[Column(Storage="_lcxfile", DbType="VarChar(100)")]
		public string lcxfile
		{
			get
			{
				return this._lcxfile;
			}
			set
			{
				if ((this._lcxfile != value))
				{
					this._lcxfile = value;
				}
			}
		}
		
		[Column(Storage="_sourcestring", DbType="VarChar(MAX)")]
		public string sourcestring
		{
			get
			{
				return this._sourcestring;
			}
			set
			{
				if ((this._sourcestring != value))
				{
					this._sourcestring = value;
				}
			}
		}
		
		[Column(Storage="_comments", DbType="VarChar(8000)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this._comments = value;
				}
			}
		}
		
		[Column(Storage="_lsresid", DbType="VarChar(512)")]
		public string lsresid
		{
			get
			{
				return this._lsresid;
			}
			set
			{
				if ((this._lsresid != value))
				{
					this._lsresid = value;
				}
			}
		}
		
		[Column(Storage="_targetculture", DbType="VarChar(10)")]
		public string targetculture
		{
			get
			{
				return this._targetculture;
			}
			set
			{
				if ((this._targetculture != value))
				{
					this._targetculture = value;
				}
			}
		}
		
		[Column(Storage="_runID", DbType="Int")]
		public System.Nullable<int> runID
		{
			get
			{
				return this._runID;
			}
			set
			{
				if ((this._runID != value))
				{
					this._runID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
