//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Localization.LocSolutions.Cerberus.Configurator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Localization.LocSolutions.Cerberus.Configurator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit. (Unsaved changes to the database will be lost.).
        /// </summary>
        public static string ConfirmApplicationExit {
            get {
                return ResourceManager.GetString("ConfirmApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database was not updated..
        /// </summary>
        public static string DatabaseNotUpdated {
            get {
                return ResourceManager.GetString("DatabaseNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database update finished..
        /// </summary>
        public static string DatabaseUpdateFinished {
            get {
                return ResourceManager.GetString("DatabaseUpdateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration data file cannot be located..
        /// </summary>
        public static string DataFileDoesNotExist {
            get {
                return ResourceManager.GetString("DataFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlistment detected at: {0}..
        /// </summary>
        public static string EnlistmentDetectedFormat {
            get {
                return ResourceManager.GetString("EnlistmentDetectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 14 enlistment not detected..
        /// </summary>
        public static string EnlistmentNotDetected {
            get {
                return ResourceManager.GetString("EnlistmentNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet implemented..
        /// </summary>
        public static string FeatureNotImplementedString {
            get {
                return ResourceManager.GetString("FeatureNotImplementedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded data from Configuration.xml.
        /// </summary>
        public static string LoadedData {
            get {
                return ResourceManager.GetString("LoadedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data from Configuration.xml.
        /// </summary>
        public static string LoadingDataInDataInProgress {
            get {
                return ResourceManager.GetString("LoadingDataInDataInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerberus Admin Config Tool v{0}.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerberus.
        /// </summary>
        public static string MessageBoxHeader {
            get {
                return ResourceManager.GetString("MessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved data to Configuration.xml.
        /// </summary>
        public static string SavedData {
            get {
                return ResourceManager.GetString("SavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save your changes because: {0} If this file is under version control, make sure you check it out first, then try saving again..
        /// </summary>
        public static string SaveFileFailedFormat {
            get {
                return ResourceManager.GetString("SaveFileFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data to Configuration.xml.
        /// </summary>
        public static string SavingDataInProgress {
            get {
                return ResourceManager.GetString("SavingDataInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating database....
        /// </summary>
        public static string UpdatingDatabase {
            get {
                return ResourceManager.GetString("UpdatingDatabase", resourceCulture);
            }
        }
    }
}
