// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.UIExtensions.#AddGridItem`1(System.Windows.Controls.Grid,System.Int32,!!0)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.UIExtensions.#ToList`1(System.Windows.Controls.ItemCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.UIExtensions.#ToList`1(System.Windows.Controls.ItemCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.UIExtensions.#ToList`1(System.Windows.Controls.UIElementCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.UIExtensions.#ToList`1(System.Windows.Controls.UIElementCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.ConfigurationSummaryViewHandler.#AddCheckEnablementInfo(System.Windows.Controls.ItemsControl,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.ConfigurationSummaryViewHandler.#AddCheckEnablementInfo(System.Windows.Controls.ItemsControl,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.ConfigurationSummaryViewHandler.#AddCheckEnablementInfoForProjects(System.Windows.Controls.ItemsControl,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.ContextData.#ToString()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.LanguageTagItem.#.ctor(System.String,Microsoft.Localization.LocSolutions.Cerberus.Core.CheckConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.MainWindow.#CommitDataToDatabase()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.MainWindow.#InitializeTitleBar()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.MainWindow.#ShowEnlistmentStatusOnStatusBar()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.PartialCheck.#.ctor(System.String,Microsoft.Localization.LocSolutions.Cerberus.Core.CheckConfiguration,System.Collections.Generic.IEnumerable`1<System.String>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Microsoft.Localization.LocSolutions.Cerberus.Configurator.ViewHandler.#AddOptionalTagIconWithTooltip(System.Windows.Controls.Panel,System.Collections.Generic.IEnumerable`1<System.String>)")]
