CREATE TABLE [dbo].[Checks](
	[ID] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[SourceCode] [text] NOT NULL,
	[Description] [text] NULL,
 CONSTRAINT [PK_Checks] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]