CREATE TABLE [dbo].[CheckTags](
	[ID] [int] NOT NULL,
	[CheckID] [int] NOT NULL,
	[TagID] [int] NOT NULL,
 CONSTRAINT [PK_CheckTags] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


